### ISSUE TITLE
more image pose pairs

### ISSUE THREAD

**Issue by boni-hu** [HKUST-Aerial-Robotics/MVDepthNet#10]
Dear WANG-KX,
  Thanks for you great project, I have used two image pose pairs to predict depth, the result is not  very good, now I want to know how to use more than two image pose pairs to predict depth.
 Thanks for you reply.

Sincerely,
HuBoni

**Comment by WANG-KX** [comment]
It's pretty simple. Just take the average of [the cost volume] from different pairs (make sure the left images are the same)(https://github.com/HKUST-Aerial-Robotics/MVDepthNet/blob/7a13790369559a365ee0fd914f12cfb3524c759b/depthNet_model.py#L139) and put it into the net.

**Comment by boni-hu** [comment]
Dear,
   Thank you very much. I used ten measurement frames and one reference frame  to compute cost volume,and predict depth ,as result the depth slightly better than two pictures.Should there be more pictures to compute costvolume?
Sincerely,
Huboni

**Comment by WANG-KX** [comment]
Dear, 
I think 10 images are far more than 'enough'. As far as I think, high-quality images with good pose estimations are equally important. If you are in forward/backward movements, more images can help. If you have left/right stereo-like configuration, ten images are enough.

**Comment by boni-hu** [comment]
Okay,thank you very much!

Huboni
