### ISSUE TITLE
train data about pkl

### ISSUE THREAD

**Issue by boni-hu** [HKUST-Aerial-Robotics/MVDepthNet#11]
Dear,
Thank for your help, and I want to train TUM dataset  use the train code you offered. But i don't know the construct about the pkl data. How to create the pkl file from origin dataset. Do you have this code? 
Yours sincerely,
HuBoni

**Comment by WANG-KX** [comment]
Check this out!
[TUM_loader.tar.gz](https://github.com/HKUST-Aerial-Robotics/MVDepthNet/files/2801624/TUM_loader.tar.gz)

**Comment by boni-hu** [comment]
Dear,
   Thank you for your help,firstly.And sorry I can't reply timely.Last but not Least,I want to know the class about Quaternion.
![image](https://user-images.githubusercontent.com/37893834/52941889-c6888680-33a4-11e9-8377-6624b4e8f96f.png)

**Comment by boni-hu** [comment]
The details of picture as follows:





At 2019-01-28 14:14:43, "WANG KAIXUAN" <notifications@github.com> wrote:


Check this out!
TUM_loader.tar.gz

**Comment by WANG-KX** [comment]
It is a Python package. Just google pyquaternion to see more information.

**Comment by boni-hu** [comment]
Thank you!

**Comment by boni-hu** [comment]
Thank you for your help,sincerely!  And, can I see what the training data you use to generate pkl data looks like?
![tumdata](https://user-images.githubusercontent.com/37893834/52986829-ee72fb00-3433-11e9-9648-8cc1ccb468f7.png)

**Comment by boni-hu** [comment]
Thank you,
Sorry to bother you many times, I have already generate the .pkl data.
Thank you again!
