### ISSUE TITLE
scene id list in SceneNN dataset

### ISSUE THREAD

**Issue by matsuren** [HKUST-Aerial-Robotics/MVDepthNet#12]
Thank you for making your project available. It's really helpful. I just want to compare my model with your MVDepthNet but scene id list in SceneNN used in your paper is not mentioned. Could you tell me which scene of SceneNN you used for training and testing?

**Comment by WANG-KX** [comment]
Thanks for your interest！

test_sequence = ['525', '093', '526', '614', '045', '015', '081', '071', '617']
train_sequence = ['005', '700', '207', '073', '337', '240', '237', '205', '263', '276', '014', '089', '021', '613', '260', '279', '528', '234', '096', '286', '041', '521', '217', '066', '036', '011', '065', '322', '607', '209', '255', '069', '265', '272', '092', '032', '025', '610', '054', '047', '225', '202', '076', '057', '527', '060', '273', '252', '080', '201', '231', '311', '270', '016', '251', '109', '078', '213', '227', '622', '030', '082', '294', '611', '522', '074', '087', '086', '061', '052', '623', '621', '084', '043', '062', '243', '246', '524', '098', '249', '038', '308', '609', '206', '223']

**Comment by matsuren** [comment]
Thanks for your quick reply.

**Comment by matsuren** [comment]
Sorry to bother you again. When you extract images and depths using 'playback' how do you associate them with trajectory? They mentioned here (https://github.com/scenenn/scenenn/issues/3) "The frame ID here is simply used for counting in the synchronized video.", but the number of images and the number of poses are different.
Ex. in scene '525', there are 2,529 images and depths while there are 2,500 poses in trajectory.log

**Comment by WANG-KX** [comment]
Dear,
I have the “depth02529.png” of scene 525. I don't know why this is different. Here I attach the image pair selection code. Hope it can help you.
Also, I am leaving on holiday for two weeks. Maybe cannot replay issues in time.
 Kaixuan

[dataset_generator.tar.gz](https://github.com/HKUST-Aerial-Robotics/MVDepthNet/files/2821729/dataset_generator.tar.gz)

**Comment by matsuren** [comment]
Thanks a lot! I will try your selection code.
