### ISSUE TITLE
TUM validate dataset

### ISSUE THREAD

**Issue by boni-hu** [HKUST-Aerial-Robotics/MVDepthNet#14]
Dear,
How to get the TUM validate dataset from original TUM dataset? What is the proportion?

Thank you

**Comment by WANG-KX** [comment]
The following is used to test the depth net:
rgbd_dataset_freiburg1_desk
rgbd_dataset_freiburg2_flowerbouquet
rgbd_dataset_freiburg2_pioneer_slam2
rgbd_dataset_freiburg2_xyz
rgbd_dataset_freiburg3_cabinet
rgbd_dataset_freiburg3_nostructure_texture_far

The following is used for training:
rgbd_dataset_freiburg1_360
rgbd_dataset_freiburg1_desk2
rgbd_dataset_freiburg1_floor
rgbd_dataset_freiburg1_plant
rgbd_dataset_freiburg1_room
rgbd_dataset_freiburg1_rpy
rgbd_dataset_freiburg1_teddy
rgbd_dataset_freiburg1_xyz
rgbd_dataset_freiburg2_coke
rgbd_dataset_freiburg2_desk
rgbd_dataset_freiburg2_dishes
rgbd_dataset_freiburg2_flowerbouquet_brownbackground
rgbd_dataset_freiburg2_large_no_loop
rgbd_dataset_freiburg2_large_with_loop
rgbd_dataset_freiburg2_metallic_sphere
rgbd_dataset_freiburg2_metallic_sphere2
rgbd_dataset_freiburg2_pioneer_360
rgbd_dataset_freiburg2_pioneer_slam
rgbd_dataset_freiburg2_pioneer_slam3
rgbd_dataset_freiburg2_rpy
rgbd_dataset_freiburg3_large_cabinet
rgbd_dataset_freiburg3_long_office_household
rgbd_dataset_freiburg3_nostructure_notexture_far
rgbd_dataset_freiburg3_nostructure_notexture_near_withloop
rgbd_dataset_freiburg3_nostructure_texture_near_withloop
rgbd_dataset_freiburg3_structure_notexture_far
rgbd_dataset_freiburg3_structure_notexture_near
rgbd_dataset_freiburg3_structure_texture_far
rgbd_dataset_freiburg3_teddy

**Comment by boni-hu** [comment]
OK,Thank you!
