### ISSUE TITLE
Problem with running example.py

### ISSUE THREAD

**Issue by rajagopalsugumar** [HKUST-Aerial-Robotics/MVDepthNet#15]
Hey,

Thank you so much for making the code public and accessible. However, when I try to implement it an error pops up "_pickle.UnpicklingError: unpickling stack underflow". I am attaching a screenshot. Can you figure out and help me with this. 

Thanks in advance !
Rajagopal Sugumar

Attch: 
https://user-images.githubusercontent.com/38287816/56172448-836b1e00-5fb7-11e9-8f3c-65c1915c96dc.PNG

**Comment by WANG-KX** [comment]
https://stackoverflow.com/questions/23964048/python-unpickling-stack-underflowMaybe the file is corrupted, please download again.
