### ISSUE TITLE
how to find the camera intrinsic  and the relative camera pose

### ISSUE THREAD

**Issue by vigneshgig** [HKUST-Aerial-Robotics/MVDepthNet#16]
you mentioned that to use own dataset you have get the camera parameter can you suggest any any tutorial regarding this camera parameter estimation and also I have one more doubt what is camera_k in example2.py how to find that camera_k parameter .

Thanks

**Comment by WANG-KX** [comment]
camera calibration can be found here: https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html
and the relative pose can be solved by VIO tracker, for example, [VINS-Mono](https://github.com/HKUST-Aerial-Robotics/VINS-Mono).

**Comment by vigneshgig** [comment]
Thanks for the reply,
I want to find left pose , right pose and camera_k for my own dataset or any other parameter i have to find
is camera_k array is relative pose.

**Comment by WANG-KX** [comment]
well, I don't understand what do you mean...

**Comment by vigneshgig** [comment]
in example2.py there is a array (camera_k) what is it represent
camera_k = np.asarray([ [525.0, 0, 319.5],
                        [0, 525.0, 239.5],
                        [0, 0, 1]])

**Comment by WANG-KX** [comment]
This is the camera matrix, also known as the intrinsic matrix.
Camera poses are also referred as extrinsic matrix.
