### ISSUE TITLE
what dataset and parameters do you use for training?

### ISSUE THREAD

**Issue by lawsonsli** [HKUST-Aerial-Robotics/MVDepthNet#18]
I used TUM rgbd dataset for training. After about 100 epoch, this is an  image pair example in training dataset.
![pred_result](https://user-images.githubusercontent.com/18007584/63321029-7b1c4a00-c2ed-11e9-8cc8-f426f87c1bbb.png)
It is not that good as you mentioned.
So, what dataset do you use for training? TUM (including dynamic objects), Nyu v2 or some else? And the training parameters? 
Thanks for your great job. It helps a lot.

**Comment by WANG-KX** [comment]
I think the details are included in the paper, you can refer to it. https://arxiv.org/abs/1807.08563.

**Comment by lawsonsli** [comment]
Thanks. I'll try that. I'd appreciate it if can you share the script of processing SUN3D dataset.

**Comment by WANG-KX** [comment]
Sorry, I searched carefully and I think I have lost the script of that path. It has been a long time since the project.
In my current opinion, I recommend you directly use the dataset provided by DeMoN to train your network. It will ease your effort if you want to publish your work.

**Comment by lawsonsli** [comment]
Thanks a lot! 
Sincerely.

**Comment by lawsonsli** [comment]
I have another question. When doing image standardization, I don't know the mean and std of the whole DeMon dataset. I don't know how to deal with this. can I use mean and std of current image instead?

**Comment by WANG-KX** [comment]
You can use the mean and std from ImageNet dataset. I think it's mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225]. From https://pytorch.org/docs/stable/torchvision/models.html
