### ISSUE TITLE
Dataset appears corrupted

### ISSUE THREAD

**Issue by mpottinger** [HKUST-Aerial-Robotics/MVDepthNet#20]
Hello, when I try to download the dataset and the pretrained models, the files appear to be corrupted, any idea what is wrong? Could you make them available somewhere else? Also, I would really like to train this model if possible! 
Thanks.

**Comment by WANG-KX** [comment]
Hi, you mean download from [this page?](https://github.com/lmb-freiburg/demon/tree/master/datasets).
If it's corrupted, I suggest you download it again. Since I did not find any problem in my downloaded file, I think it's caused by the internet instead of the source file.

You can train the model if you want.

**Comment by mpottinger** [comment]
@WANG-KX here is where I tried to download:

2.0 Download the model parameters and the samples

We provide a trained model used in our paper evaluation and some images to run the example code.

Please download the model via the link
https://www.dropbox.com/s/o1n1w0chlrw4lqt/opensource_model.pth.tar?dl=0


 and the sample images via the link. 

https://www.dropbox.com/s/hr59f24byc3x8z3/sample_data.pkl.tar.gz?dl=0

Put the model opensource_model.pth.tar and extract the sample_data.pkl.tar.gz under the project folder.

Dropbox says something is wrong with it, and also when I tried to run the code it gave an error saying it was corrupted.

Do you mean the model/dataset from the other link you posted will also work with Mvdepthnet?

Sorry I am not really an expert but I will try again.

I didn't see any model training code but I will look closer at it.

**Comment by WANG-KX** [comment]
Hi, I thought you mean the training dataset provided by DeMoN.
I will check my dropbox link tomorrow (although I dont know what will go wrong with Dropbox).

**Comment by WANG-KX** [comment]
Hi, I checked the file you uploaded. They have the same md5sum with my files.
The model weight can be directly read by torch.load without extraction. sample_data.pkl.tar.gz should be unpacked into sample_data.pkl and read by python 2.7.

**Comment by mpottinger** [comment]
Ok thanks for checking, must be some other issue, I tried with Python 3.7

**Comment by mpottinger** [comment]
@WANG-KX after looking again, I see the issue seems to be just my unfamiliarity with Pytorch. The .tar extension was confusing for me as those are usually archives that can be extracted in Linux, but not in this case. How embarassing ;)

**Comment by WANG-KX** [comment]
Glad solving the problem(•̀ᴗ•́)و ̑̑
