### ISSUE TITLE
Problem when converting depth map to point cloud

### ISSUE THREAD

**Issue by Beniko95J** [HKUST-Aerial-Robotics/MVDepthNet#22]
Hi, I am trying to convert the predicted depth map to point cloud but I meet some problems. I use the image pair in example2.py  for test. As MVDepthNet predicts the metric inverse depth (0.02 ~ 2 m^-1), so I saved the inverse depth map normalized to 0~255 as a png image as follows. White means large inverse depth, which means the pixel is close to the camera.

![image](https://user-images.githubusercontent.com/30772597/67360126-10fb7c00-f5a0-11e9-869e-c35b9aba366c.png)

I get the depth from the saved png depth map as follows

```
double pixel_depth = (1 / (double(pixel) / 255 * (2 - 0.02) + 0.02));
```

But when I check the generated point cloud, It looks very bad, like this:

![image](https://user-images.githubusercontent.com/30772597/67360365-a72fa200-f5a0-11e9-84bb-126f20da9515.png)

![image](https://user-images.githubusercontent.com/30772597/67360382-ba427200-f5a0-11e9-8d9c-ea46b4799b92.png)

It seems like that the depth is predicted very bad, while the depth map image looks good.
Am I missing something to do the conversion correctly?

Best regards

**Comment by WANG-KX** [comment]
Well...
I think the equation is not correct ...
Just ```1.0 / predicted_inversedepth```
and saving to PNG losses to many precisions.

BTW, the predicted seems not quite smooth due to there is no smooth loss during the training. I am now doing a project that achieves the best quality motion stereo estimation on DeMoN dataset and will open-source when all the training is done.

**Comment by Beniko95J** [comment]
Thank you for the quick reply. That will be very nice. But currently do you have any advice to convert an inverse depth map to point cloud without much precision degeneration?

**Comment by WANG-KX** [comment]
If you must save the map first, you can use numpy.save() to save in a float32 format.

**Comment by Beniko95J** [comment]
By saving the inverse depth map in float32 format, I got a better result. Thank you for the advice and look forward to seeing your next work!
