### ISSUE TITLE
run example.py problem

### ISSUE THREAD

**Issue by GuoChuan1314** [HKUST-Aerial-Robotics/MVDepthNet#25]
When I run example.py,there is a UnpicklingError.

  File "G:/GroupMeet/Depth_problem/MVDepthNet-master/example.py", line 19, in <module>
    sample_datas = pickle.load(fp)

UnpicklingError: invalid load key, ''.

How can I solve it?
The data is error ?

Can you help me?

**Comment by WANG-KX** [comment]
Please use python 2.7.

**Comment by GuoChuan1314** [comment]
thank you
