### ISSUE TITLE
Problem about the selection strategy for the dataset

### ISSUE THREAD

**Issue by TangRuijie** [HKUST-Aerial-Robotics/MVDepthNet#26]
Hi, thanks for your great work!
Recently I am working on my project and I want to use the same dataset as your work's. In your paper you mentioned the selection strategy for the dataset. Specifically, "at least 70% of the pixels in the reference image should be visible in the measurement image, and the average photo-consistency error between image pairs should be less than 80". I tried to implement the selection strategy to filter the DeMoN dataset but by now I have not got the same number of training/testing samples as you mentioned in your supplementary material. Could you elaborate the selection strategy a little? What kind of photo-consistency metrics did you use for selecting the training/testing samples? Did you compute the p-c error between rgb or gray image pairs? When computing the p-c error will you ignore the invisible pixels(pixels in the reference image which are not visible in the measurement image)? I'd appreciate it if you can reply. Thank you!

**Comment by WANG-KX** [comment]
Hi,

I post here a script to calculate the overlap and pixel difference. 
https://gist.github.com/WANG-KX/5b2fca2a03627b92700e5e470e51f88a

I think it's ok not getting the exact number of images.

Hope this helps,
Kaixuan

**Comment by TangRuijie** [comment]
Thank you for your reply and help. This really helps a lot!
