### ISSUE TITLE
About the depth of MVS test set

### ISSUE THREAD

**Issue by TangRuijie** [HKUST-Aerial-Robotics/MVDepthNet#27]
Hi,
Sorry for bothering again.
In other issues and your paper you mentioned that the depth values of the DeMoN dataset are in metric scale. I checked the depth of the dataset and most of the data are normal. However, when I checked the test set of MVS dataset, I found something wrong with the depth values. To be specific, in the MVS test set, there are some samples of a chair:
![image](https://user-images.githubusercontent.com/20614600/77390971-7a431d80-6dd2-11ea-9493-d97905d9d42c.png)
The mean depth value of corresponding depth map is about 7.4.
However, when it comes to samples of a building:
![image](https://user-images.githubusercontent.com/20614600/77391042-aced1600-6dd2-11ea-8368-607a0dd4c12c.png)
The mean depth value of corresponding depth map is only around 2.2.
This is really strange and I wonder if you noticed this problem in your experiment?
I am looking forward to your reply.

Best regards!

**Comment by TangRuijie** [comment]
When I compute the mean depth value I have already ignored the invalid pixels in the depth maps.

**Comment by WANG-KX** [comment]
Hi,
Thanks for your interest.
The source of the scale is from the relative pose. In other words, the scale is consistent with the relative pose. In MVS dataset, the relative poses are calculated via SfM methods (e.g. colmap) thus do not have correct scales. Thus, we cannot get the right scale.
Kaixuan

**Comment by TangRuijie** [comment]
Thanks for you reply!
