### ISSUE TITLE
about the .pkl data

### ISSUE THREAD

**Issue by boni-hu** [HKUST-Aerial-Robotics/MVDepthNet#4]
hello,
  Thank you for your great work first.I run the example.py successfuly, and the results are great.Now i want to run my own data,but i can't creat the data of pkl.What should i do?Do you have the source code about creating the type of data?

Best wishes!
Boni Hu

**Comment by WANG-KX** [comment]
Dear,

Thanks for your interest in this project.
The "example.py" shows how to use the network to generate depth estimation. Only three elements are required for each estimation: left image (`this_sample['left_image']`),  right image (`this_sample['right_image']`), and the relative pose (`this_sample['left2right']`). `this_sample['depth_image']` is used for evaluation only and you can omit it. Just replace these three elements in the code and everything is fine.

For more information, please see [readme](https://github.com/HKUST-Aerial-Robotics/MVDepthNet#40-use-your-own-data) and [this issue](https://github.com/HKUST-Aerial-Robotics/MVDepthNet/issues/2).

Regard,
Kaixuan
