### ISSUE TITLE
Problems using my own data

### ISSUE THREAD

**Issue by ghost** [HKUST-Aerial-Robotics/MVDepthNet#5]
Hi, thank you for the great repository! :)

I could successfully test it with your provided test labels. However I am having issues using my own data.

Here is an example of my input data:

First image (left):
![96369 798432](https://user-images.githubusercontent.com/43221338/45584073-4fb30300-b8c5-11e8-9f14-d5e9d79ccc98.jpg)

Second image (right):
![96373 464939](https://user-images.githubusercontent.com/43221338/45584080-6bb6a480-b8c5-11e8-935f-740773f8593f.jpg)

First image extrinsics and intrinsics:

```
"96369.798432.jpg": {

	"extrinsics": [[0.7245516,0.3634065,-0.5856284,1.018013],[0.05039374,0.8194891,0.5708749,0.02848812],[0.6873757,-0.4431403,0.5754488,-0.4639755],[0,0,0,0.9999999]],

	"imageName": "96369.798432.jpg",

	"intrinsics": [[1619.542,0,959.5],[0,1619.542,539.5],[0,0,1]],

	"timeStamp": 96369.798432

}
```

Second image intrinsics and extrinsics:

```
"96373.464939.jpg": {

	"extrinsics": [[0.4488778,0.404342,-0.7968791,1.488057],[0.02514287,0.8857014,0.4635739,0.05461761],[0.8932394,-0.2281239,0.3874055,-0.3899191],[0,0,0,1]],

	"imageName": "96373.464939.jpg",

	"intrinsics": [[1619.076,0,959.5],[0,1619.076,539.5],[0,0,1]],

	"timeStamp": 96373.464938666

}
```

But the result is:

![96370 131751-96373 464939](https://user-images.githubusercontent.com/43221338/45584118-2fd00f00-b8c6-11e8-847d-b07fa3572e7b.jpg)

This is just an example result; I am getting the same wrong results on all of my images.

Any ideas how I could solve it? Thanks! :)

**Comment by WANG-KX** [comment]
Dear,

Thanks for your interest in the project. 
I would like to help you with this image pair. However, I have a nearby deadline this week. When I finish the deadline, I will take a look at what happened here. Apology for not helping in time.

Regards,
Kaixuan

**Comment by ghost** [comment]
@WANG-KX thank you for the quick reply, and no worries; I look forward to hearing from you once you've completed your deadline :)

**Comment by WANG-KX** [comment]
Hi,

I have updated the code. You can find the code in ```example2.py``` about how to use your data. If the result is still not good please check the relative pose quality. I have tested your data, it seems that the pose is not correct. At least not the camera pose in the world frame.

Regards,

Kaixuan
